name: CI way

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 1. do git pull
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup Java (PetClinic is Java app)
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Build application
    - name: Build with Maven
      run: mvn clean install -DskipTests -Dcheckstyle.skip=true

    # 4. Build Docker image
    - name: Build Docker image
      run: docker build -t project:v1 .





